//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1.DLSyncService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DLSyncService.DatabaseSyncServiceSoap")]
    public interface DatabaseSyncServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReceiveMessage(string message, long sequenceNumber, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReceiveMessageAsync(string message, long sequenceNumber, string tableName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DatabaseSyncServiceSoapChannel : WindowsService1.DLSyncService.DatabaseSyncServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseSyncServiceSoapClient : System.ServiceModel.ClientBase<WindowsService1.DLSyncService.DatabaseSyncServiceSoap>, WindowsService1.DLSyncService.DatabaseSyncServiceSoap {
        
        public DatabaseSyncServiceSoapClient() {
        }
        
        public DatabaseSyncServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseSyncServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseSyncServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseSyncServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string ReceiveMessage(string message, long sequenceNumber, string tableName) {
            return base.Channel.ReceiveMessage(message, sequenceNumber, tableName);
        }
        
        public System.Threading.Tasks.Task<string> ReceiveMessageAsync(string message, long sequenceNumber, string tableName) {
            return base.Channel.ReceiveMessageAsync(message, sequenceNumber, tableName);
        }
    }
}
